In [1]:
import pandas as pd

raw_path = "../data/raw/churn.csv"

df = pd.read_csv(raw_path)

print("Shape:", df.shape)
df.head()

Shape: (1002, 8)

,customer_id,age,tenure_months,monthly_charges,support_calls,contract_type,usage_hours,churn
0,C0001,56.0,35,103.62,2,Monthly,19.6,1
1,C0002,69.0,51,104.89,0,Yearly,17.5,1
2,C0003,46.0,15,75.67,3,Monthly,119.1,1
3,C0004,32.0,25,30.57,1,Monthly,84.7,0
4,C0005,60.0,55,55.83,1,Monthly,15.4,0

In [3]:
df.isnull().sum()

customer_id        0
age                1
tenure_months      0
monthly_charges    1
support_calls      0
contract_type      1
usage_hours        0
churn              0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(2)

In [5]:
df = df.drop_duplicates()

In [6]:
print("Shape after removing duplicates:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

Shape after removing duplicates: (1000, 8)
Duplicates remaining: 0

In [7]:
numeric_cols = [
    "age",
    "tenure_months",
    "monthly_charges",
    "support_calls",
    "usage_hours"
]

In [8]:
df["age"] = df["age"].fillna(df["age"].median())

df["monthly_charges"] = df["monthly_charges"].fillna(
    df["monthly_charges"].median()
)

In [9]:
df[numeric_cols].isnull().sum()

age                0
tenure_months      0
monthly_charges    0
support_calls      0
usage_hours        0
dtype: int64

In [10]:
df["contract_type"].value_counts()

contract_type
Monthly     547
Yearly      318
Two-Year    134
Name: count, dtype: int64

In [11]:
df["contract_type"] = df["contract_type"].fillna(
    df["contract_type"].mode()[0]
)

In [12]:
df["contract_type"].isnull().sum()

np.int64(0)

In [13]:
df.isnull().sum()

customer_id        0
age                0
tenure_months      0
monthly_charges    0
support_calls      0
contract_type      0
usage_hours        0
churn              0
dtype: int64

In [15]:
df.iloc[df["monthly_charges"] > 200]

,customer_id,age,tenure_months,monthly_charges,support_calls,contract_type,usage_hours,churn
70,C0071,23.0,31,999999.0,4,Yearly,150.2,1

In [17]:
import numpy as np
df.loc[
    (df["monthly_charges"] < 0) |
    (df["monthly_charges"] > 200),
    "monthly_charges"
] = np.nan

In [18]:
df["monthly_charges"].isnull().sum()

np.int64(1)

In [19]:
df["monthly_charges"] = df["monthly_charges"].fillna(
    df["monthly_charges"].median()
)

In [20]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (1000, 8)

Missing values:
customer_id        0
age                0
tenure_months      0
monthly_charges    0
support_calls      0
contract_type      0
usage_hours        0
churn              0
dtype: int64

Duplicates:
0

Data types:
customer_id            str
age                float64
tenure_months        int64
monthly_charges    float64
support_calls        int64
contract_type          str
usage_hours        float64
churn                int64
dtype: object

In [21]:
df.head()

,customer_id,age,tenure_months,monthly_charges,support_calls,contract_type,usage_hours,churn
0,C0001,56.0,35,103.62,2,Monthly,19.6,1
1,C0002,69.0,51,104.89,0,Yearly,17.5,1
2,C0003,46.0,15,75.67,3,Monthly,119.1,1
3,C0004,32.0,25,30.57,1,Monthly,84.7,0
4,C0005,60.0,55,55.83,1,Monthly,15.4,0

In [22]:
from pathlib import Path

processed_path = Path("../data/processed")
processed_path.mkdir(parents=True, exist_ok=True)

df.to_csv(processed_path / "cleaned_data.csv", index=False)

print("Cleaned data saved successfully!")
print("Path:", processed_path / "cleaned_data.csv")
print("Shape:", df.shape)

Cleaned data saved successfully!
Path: ..\data\processed\cleaned_data.csv
Shape: (1000, 8)